namespace GorenjeDashboard.Migrations
{
    using Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<GorenjeDashboard.Models.GorenjeDBContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "GorenjeDashboard.Models.GorenjeDBContext";
        }

        protected override void Seed(GorenjeDashboard.Models.GorenjeDBContext context)
        {
            //  This method will be called after migrating to the latest version.

            context.Palletes.AddOrUpdate(p => p.PalleteName,
                                new PalleteModel() { PalleteName = "Euro Paleta" },
                                new PalleteModel() { PalleteName = "Velika mrežasta paleta" },
                                new PalleteModel() { PalleteName = "Mala mrežasta paleta" },
                                new PalleteModel() { PalleteName = "Velika kovinska paleta" },
                                new PalleteModel() { PalleteName = "Mala kovisnka paleta" });

            context.Machines.AddOrUpdate(m => m.Machine,
                            new MachineModel() { Machine = "Rg-1" },
                            new MachineModel() { Machine = "Rg-2" },
                            new MachineModel() { Machine = "Trumph" },
                            new MachineModel() { Machine = "HFE" },
                            new MachineModel() { Machine = "HFB" },
                            new MachineModel() { Machine = "Laser 1" },
                            new MachineModel() { Machine = "Laser 2" },
                            new MachineModel() { Machine = "Prebijalka 1" },
                            new MachineModel() { Machine = "Prebijalka 2" },
                            new MachineModel() { Machine = "Prebijalka 3" });


        //    context.Materials.AddOrUpdate(m => m.Material,
        //new MaterialModel() { Material = "NOSILEC HV NG603,NG503-PLATINA", MaterialCode = "433361", MaterialStructure = "630263", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 1").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV DNA 75A M", MaterialCode = "294337", MaterialStructure = "322631", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 1").MachineId },
        //new MaterialModel() { Material = "VODILO STENE KANALA ZRAKA 75A M-PLATINA", MaterialCode = "301358", MaterialStructure = "301505", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 1").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV VOD.POSODE VRAT 75A M-PLATINA", MaterialCode = "301375", MaterialStructure = "130282", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 1").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA ALU IG9571-PLATINA", MaterialCode = "515567", MaterialStructure = "286371", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "NOSILEC TC LITE BI2 NGVK3-PLATINA", MaterialCode = "379256", MaterialStructure = "343479", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "KOTNIK DNA LEVI 75A M-PLATINA", MaterialCode = "301310", MaterialStructure = "322617", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "NOSILEC TRANSFORMATORJA WMD 70-PLATINA", MaterialCode = "420498", MaterialStructure = "322617", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "NOSILEC MODULA TOUCH NGVK3-SORNIK", MaterialCode = "306931", MaterialStructure = "630264", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "NOSILEC PRIKAZOVALNIKA BI2-PLATINA", MaterialCode = "379268", MaterialStructure = "343479", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "KANAL SESALNI BI2 LEVI-PLATINA", MaterialCode = "379262", MaterialStructure = "187098", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "KANAL SESALNI BI2 DESNI-PLATINA", MaterialCode = "379264", MaterialStructure = "370363", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "OHIŠJE NOSILNO BI2 603 SERVIS PLATINA", MaterialCode = "563429", MaterialStructure = "343479", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 3").MachineId },
        //new MaterialModel() { Material = "POKROV KP-HS-OU-E-SEKAN", MaterialCode = "155993", MaterialStructure = "100670", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 1").MachineId },
        //new MaterialModel() { Material = "PLOÈEVINA PREGRADNA NGVA3-2-PIRO", MaterialCode = "419959", MaterialStructure = "481319", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 1").MachineId },
        //new MaterialModel() { Material = "NOSILEC RB-PLATINA", MaterialCode = "472380", MaterialStructure = "322631", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 1").MachineId },
        //new MaterialModel() { Material = "OHIŠJE KATALIZATORJA", MaterialCode = "303992", MaterialStructure = "643204", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 1").MachineId },
        //new MaterialModel() { Material = "NOSILEC MODULA EPM 1.2-PLATINA", MaterialCode = "473911", MaterialStructure = "343479", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV HZFI GOI2", MaterialCode = "246392", MaterialStructure = "661228", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV ROÈAJA A6 RM88 STR- PLATINA", MaterialCode = "461914", MaterialStructure = "338172", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV ROÈAJA A6 RM88/9 SRE- PLATINA", MaterialCode = "461911", MaterialStructure = "338172", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV VRAT PREDALA ZO D 75A M-PLATINA", MaterialCode = "301621", MaterialStructure = "661192", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "PLOÈEVINA PREGADNA BIO PIRO 45/60", MaterialCode = "439431", MaterialStructure = "438908", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "STRANICA PREDALA DP SPD-PLATINA", MaterialCode = "143971", MaterialStructure = "130282", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OBOD PREDALA DP SPD PLATINA", MaterialCode = "143972", MaterialStructure = "130258", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "OBOD PREDALA DP ZG.PLATINA", MaterialCode = "143907", MaterialStructure = "130258", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "DNO NGVK3 SVK6-TOUCH ATAG MEKOM", MaterialCode = "303247", MaterialStructure = "227706", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA ÈELNA NG603 PCFS F6-40 SUR.LUÈKA", MaterialCode = "493250", MaterialStructure = "493249", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-PV90 L440 H30 VZ065-PLATINA", MaterialCode = "462387", MaterialStructure = "462393", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-PV48 L440 H10 VZ065-PLATINA", MaterialCode = "462392", MaterialStructure = "462393", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-SP3-S-L481 H15 VZ065-PLATINA", MaterialCode = "462385", MaterialStructure = "462393", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "VRATA ZUNANJA FI/BI XL F.SL PLATINA", MaterialCode = "569417", MaterialStructure = "546378", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "POKROV STIKALA 78_02_2507-PLATINA  ", MaterialCode = "522061", MaterialStructure = "176508", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC RAÈUNALNIKA 78_04_2114-PLATINA  ", MaterialCode = "522198", MaterialStructure = "176508", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC RAÈUNALNIKA D 78_21_2108 PLATINA  ", MaterialCode = "564280", MaterialStructure = "176508", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Laser 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_02_2506-PLATINA  ", MaterialCode = "522060", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA STRANSKA PT 78_02_2201C", MaterialCode = "514839", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "PCB NOSILEC 78_05_2301H", MaterialCode = "514770", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA POKROVA PT 78_04_2201A-PLATINA", MaterialCode = "522103", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA SPODNJA 78_04_2201B", MaterialCode = "514841", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC ŠTEVCEV ZG.78_04_2101AH-PLATINA", MaterialCode = "522109", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_04_2101BE-PLATINA", MaterialCode = "522119", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC DESNI 78_21_2301C PLATINA", MaterialCode = "564285", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B PLATIN", MaterialCode = "564286", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC LEVI 78_21_2301A PLATINA", MaterialCode = "564287", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B PLATIN", MaterialCode = "564286", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B PLATIN", MaterialCode = "564286", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_21_2101Y PLATINA", MaterialCode = "564289", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC KLJUÈAVNICE D 78_21_2101P PLATIN", MaterialCode = "564388", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC KLJUÈAVNICE L 78_21_2101R PLATIN  ", MaterialCode = "564298", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC CA 78_21_2101U", MaterialCode = "559388", MaterialStructure = "176509", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "ROÈICA TEÈAJA 78_05_2305B  ", MaterialCode = "514713", MaterialStructure = "100801", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "NOSILEC TEÈAJA 78_05_2305A  ", MaterialCode = "514710", MaterialStructure = "534589", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA TEÈAJA 78_05_2304A", MaterialCode = "514720", MaterialStructure = "534609", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Prebijalka 2").MachineId },
        //new MaterialModel() { Material = "ALU PLOŠÈA 774x484 SIVK8BTF", MaterialCode = "280878", MaterialStructure = "316621", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC ARMATURE 90CM", MaterialCode = "498303", MaterialStructure = "498972", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC OKVIRJA D-UPOGNJEN", MaterialCode = "115666", MaterialStructure = "100708", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC OKVIRJA L-UPOGNJEN", MaterialCode = "115668", MaterialStructure = "100709", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "PROFIL SVK 71", MaterialCode = "135352", MaterialStructure = "146200", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC ŠTEVCEV ZG 78_04_2101AH  ", MaterialCode = "515056", MaterialStructure = "522109", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_21_2101Y", MaterialCode = "559384", MaterialStructure = "564289", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC KLJUÈAVNICE D 78_21_2101P", MaterialCode = "560990", MaterialStructure = "564388", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC KLJUÈAVNICE L 78_21_2101R  ", MaterialCode = "559419", MaterialStructure = "564298", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "POKROV STIKALA 78_02_2507  ", MaterialCode = "514429", MaterialStructure = "522061", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC PL.ÈEL.BIO STEAM TFT/DOT MAT KPL", MaterialCode = "437758", MaterialStructure = "445377", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "NOSILEC GPP 6-43-44 H&S LEVI STEKLO", MaterialCode = "414087", MaterialStructure = "416221", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-1").MachineId },
        //new MaterialModel() { Material = "POKROV KP HS OU E", MaterialCode = "139423", MaterialStructure = "155993", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "NOSILEC OJAÈITVE 78_05_2303  ", MaterialCode = "514726", MaterialStructure = "522062", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_02_2506  ", MaterialCode = "514374", MaterialStructure = "522060", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "NOSILEC", MaterialCode = "702596", MaterialStructure = "436335", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "POSODA PREDALA SKANDINAVIJA-UPOGNJEN", MaterialCode = "316570", MaterialStructure = "316569", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV ROÈAJA A6 RM88 STR", MaterialCode = "459176", MaterialStructure = "461914", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV ROÈAJA A6 RM88/9 SRE", MaterialCode = "458592", MaterialStructure = "461911", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "NOSILEC VENTILATORJA L", MaterialCode = "183615", MaterialStructure = "196510", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Rg-2").MachineId },
        //new MaterialModel() { Material = "VODILNIK ZRAKA SESALNI-SPD PIRO.HF", MaterialCode = "431333", MaterialStructure = "433199", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "OKVIR FIKSNI ATAG KAVNI AVTOMAT  ", MaterialCode = "527333", MaterialStructure = "527388", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "OKVIR FIKSNI ATAG BIO45 TFT MATRIX VZ065", MaterialCode = "474134", MaterialStructure = "516993", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "NALEPEK ST.PL.ÈELNE FL PELGRIM VZ065", MaterialCode = "495224", MaterialStructure = "497681", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "POKROV PREDALNIKA REZERVOARJA VODE BIO", MaterialCode = "438274", MaterialStructure = "444419", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV VRAT PREDALA ZO D 75A", MaterialCode = "295070", MaterialStructure = "301621", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "NOSILEC PLOŠÈE MONT.SPR.60/90", MaterialCode = "475112", MaterialStructure = "476921", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "OKVIR FIKS.ATAG BIO45 TMX STEAM", MaterialCode = "504958", MaterialStructure = "516995", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "OKVIR FIKS.ATAG BIO45 TMX", MaterialCode = "506616", MaterialStructure = "516999", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-PV90 L440 H30 VZ065", MaterialCode = "459304", MaterialStructure = "462387", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-PV48 L440 H10 VZ065", MaterialCode = "459308", MaterialStructure = "462392", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "PROFIL A6-SP3-S-L481 H15 VZ065", MaterialCode = "459303", MaterialStructure = "462385", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "Trumph").MachineId },
        //new MaterialModel() { Material = "ŠÈIT PLOŠÈE 78_04_2104  ", MaterialCode = "515087", MaterialStructure = "522193", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC POKROVA 78_21_2303", MaterialCode = "559098", MaterialStructure = "564284", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC ZVOÈNIKA 78_21_2101Q", MaterialCode = "559420", MaterialStructure = "564593", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC 72_03_2101A M", MaterialCode = "563785", MaterialStructure = "574111", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC SPREDNJI 72_03_2101D M", MaterialCode = "563829", MaterialStructure = "574113", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC 72_03_2101B M", MaterialCode = "563786", MaterialStructure = "574110", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA POKROVA PT 78_04_2201A", MaterialCode = "514842", MaterialStructure = "522103", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_02_2506  ", MaterialCode = "514374", MaterialStructure = "522060", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "PLOŠÈA POKROVA PT 78_04_2201A", MaterialCode = "514842", MaterialStructure = "522103", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC STIKALA 78_04_2101BE  ", MaterialCode = "514924", MaterialStructure = "522119", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC DESNI 78_21_2301C", MaterialCode = "559096", MaterialStructure = "564285", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B", MaterialCode = "559097", MaterialStructure = "564286", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC LEVI 78_21_2301A", MaterialCode = "559095", MaterialStructure = "564287", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B", MaterialCode = "559097", MaterialStructure = "564286", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC PREÈNI TEÈAJA 78_21_2301B", MaterialCode = "559097", MaterialStructure = "564286", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC RAÈUNALNIKA 78_04_2114  ", MaterialCode = "515126", MaterialStructure = "522198", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC RAÈUNALNIKA D 78_21_2108", MaterialCode = "559430", MaterialStructure = "564280", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC GPP 6-43-44 H&S LEVI STEKLO", MaterialCode = "414087", MaterialStructure = "416221", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFB").MachineId },
        //new MaterialModel() { Material = "NOSILEC HV NG603,NG503-UPOGNJEN", MaterialCode = "443288", MaterialStructure = "443287", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "POKROV ZAŠÈITNI MKE KL", MaterialCode = "271578", MaterialStructure = "621643", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "OJAÈITEV HZFI GOI2", MaterialCode = "246392", MaterialStructure = "661228", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "NOSILEC KONZOL POLIC L 75A M", MaterialCode = "295437", MaterialStructure = "377283", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "VODILO POSODE VRAT D 75A M", MaterialCode = "295021", MaterialStructure = "377335", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "NOSILEC KONZOL POLIC D 75A VK M", MaterialCode = "317741", MaterialStructure = "377346", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "PLOÈEVINA DELILNA BIO PIRO 45/60", MaterialCode = "440874", MaterialStructure = "443417", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "NOSILEC MODULA EPM 1.2", MaterialCode = "471137", MaterialStructure = "473911", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId },
        //new MaterialModel() { Material = "NOSILEC ÈRPALK PSR-15", MaterialCode = "570959", MaterialStructure = "573697", MachineId = context.Machines.FirstOrDefault(m => m.Machine == "HFE").MachineId }
        //    );
        }
    }
}
